### ISSUE TITLE
Ethereum Phishing warning on openslo.com

### ISSUE THREAD

**Issue by benattar** [OpenSLO/openslo.github.io#3]
![image](https://user-images.githubusercontent.com/1813860/148108448-d8c9a12e-22b8-4da2-9629-844ef34b9de1.png)
Attempting to connect to openslo.com in a browser with a metamask extension flags a warning that the openslo.com website has been reported as an ethereum phishing site.

**Comment by proffalken** [comment]
@benattar - I've just searched the CryptoScamDB site for openslo.com and it's not listed anywhere.

I'm also not seeing anything untoward in the HTML source for openslo.com when visiting it in a browser and inspecting the browser console.

I should make it clear that I'm not saying "there's nothing wrong here", only that I can't find out what's causing that error - is there any chance you can post the links to the Ethereum Phishing Detector and CryptoScamDB that are mentioned in that error?

**Comment by benattar** [comment]
Pops up on any browser I have the MetaMask wallet extension on.
[image: image.png]

**Comment by ian-bartholomew** [comment]
I was able to reproduce this and filed [a ticket](https://github.com/MetaMask/eth-phishing-detect/issues/6435) with them

**Comment by programmer04** [comment]
Website openslo.com has been added to the [allow list](https://github.com/MetaMask/eth-phishing-detect/blob/1dd591fed160feca9dd9eb7a27994a3131074bdc/src/config.json#L318), thanks for submitting the issue and @ian-bartholomew for https://github.com/MetaMask/eth-phishing-detect/issues/6435
